services:
  - type: web
    name: sulfur-io-backend
    runtime: node
    plan: free
    rootDir: backend

    buildCommand: npm ci
    startCommand: npm start

    healthCheckPath: /health

    envVars:
      - key: MONGODB_CONNECTION_STRING
        sync: false