name: Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.1"
          channel: stable
          cache: true

      - name: Flutter pub get
        working-directory: frontend
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: frontend
        run: |
          flutter build web --release \
            --dart-define=BACKEND_URL=https://sulfur-io-backend.onrender.com

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
          vercel-args: --prod